client_id = "1ef2fce47497534d788eb2e4e7f37466"
name = "Maldify"
application_url = "http://localhost:45841"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

[access_scopes]
scopes = "write_products, read_orders"

[auth]
redirect_urls = [
    "http://localhost:45841/api/auth/callback",
    "http://localhost:45841/api/auth",
]