# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1ef2fce47497534d788eb2e4e7f37466"
name = "Maldify"
application_url = "https://fifty-relating-christmas-gba.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_customers,read_products,write_products,write_checkouts"

[auth]
redirect_urls = [ "https://fifty-relating-christmas-gba.trycloudflare.com/api/auth" ]

[[extensions]]
type = "ui"
name = "Admin UI"
handle = "app-admin-ui"
path = "web/frontend"

[[extensions]]
type = "post_purchase"
name = "Maldify Post-Purchase Offer"
handle = "maldify-post-purchase"
path = "src/extensions/post-purchase-upsell"